# Generated by Django 4.0.4 on 2022-04-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='default', max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='default', max_length=32),
        ),
    ]
