# Generated by Django 4.0.4 on 2022-04-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0002_post_description_alter_post_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='published', max_length=250),
        ),
    ]
