# Generated by Django 4.0.4 on 2022-04-14 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0003_post_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
